In [7]:
import numpy as np
array= np.array([[1,2,3],
                [4,2,5]])
print (array)
type (array)


[[1 2 3]
 [4 2 5]]


numpy.ndarray

In [8]:
print(array.shape)
print(array.size)
print(array.dtype)

(2, 3)
6
int32


In [9]:
print(array.ndim)

2


In [11]:
    a = np.array([[1,2,4],[5,8,7]], dtype = 'float')
    print ("array created using passed list : \n", a)

array created using passed list : 
 [[1. 2. 4.]
 [5. 8. 7.]]


In [15]:
c= np.zeros((2,3))
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
f= (np.arange(0,40,3))
f


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39])

In [28]:
np.linspace(0,5,3)

array([0. , 2.5, 5. ])

In [29]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [33]:
arr=array.reshape((3,2))
arr


array([[1, 2],
       [3, 4],
       [2, 5]])

In [36]:
arr= array+2
arr

array([[3, 4, 5],
       [6, 4, 7]])

In [37]:
arr = arr*3
arr

array([[ 9, 12, 15],
       [18, 12, 21]])

In [40]:
arr.max()

21

In [41]:
arr.sum()

87

In [42]:
arr[1:,:2]

array([[18, 12]])

In [44]:
arr= array.flatten()
arr

array([1, 2, 3, 4, 2, 5])

In [46]:
arr.max(axis=0)

5

In [53]:
a= np.array([[1,2,4],
         [3,4,5],
          [8,7,9]])
b= np.array([[2,3,4],
             [3,7,6],
             [3,5,6]])
print("Hstack\n", np.column_stack((a,b)))
print("Vstack\n", np.row_stack((a,b)))

Hstack
 [[1 2 4 2 3 4]
 [3 4 5 3 7 6]
 [8 7 9 3 5 6]]
Vstack
 [[1 2 4]
 [3 4 5]
 [8 7 9]
 [2 3 4]
 [3 7 6]
 [3 5 6]]


In [56]:
a= np.array([[1,2,3,4],[5,6,7,8]])
print("horizontal split",np.hsplit(a,2))
print("vertical split", np.vsplit(a,2))

horizontal split [array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
vertical split [array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [64]:
b=np.array([1,5,4,2,3])
print(np.median(b))
print(np.mean(b))

3.0
3.0


In [65]:
np.sqrt(b)

array([1.        , 2.23606798, 2.        , 1.41421356, 1.73205081])

In [66]:
np.exp(b)

array([  2.71828183, 148.4131591 ,  54.59815003,   7.3890561 ,
        20.08553692])

In [67]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [69]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825]])